name: Build APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            wget \
            unzip

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Cython==3.0.8
          pip install buildozer==1.5.0
          pip install --upgrade Pillow

      - name: Cache Buildozer dependencies
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Accept SDK licenses and setup Android SDK
        run: |
          yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses >/dev/null 2>&1
          /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "build-tools;34.0.0" \
            "platforms;android-34" \
            "cmdline-tools;latest" \
            "ndk;25.2.9519653" >/dev/null 2>&1

      - name: Verify buildozer.spec exists
        run: |
          if [ ! -f "buildozer.spec" ]; then
            echo "Creating default buildozer.spec"
            buildozer init
            # Update the spec file with required settings
            sed -i 's/^android.archs.*/android.archs = arm64-v8a, armeabi-v7a/' buildozer.spec
            sed -i 's/^#android.ndk.*/android.ndk = 25.2.9519653/' buildozer.spec
            sed -i 's/^#android.sdk.*/android.sdk = 34/' buildozer.spec
            sed -i 's/^#android.build_tools.*/android.build_tools = 34.0.0/' buildozer.spec
          fi

      - name: Build APK
        run: |
          # Clear previous build if exists
          rm -rf bin/*.apk || true
          # Build with limited log output
          buildozer android debug 2>&1 | tee build.log
          echo "Showing last 100 lines of build log:"
          tail -n 100 build.log
          
          # Check if APK was actually generated
          if ! ls bin/*.apk 1> /dev/null 2>&1; then
            echo "Error: APK was not generated"
            echo "Searching for errors in build log:"
            grep -i "error\|exception\|failed" build.log | tail -n 10
            exit 1
          else
            echo "APK generated successfully:"
            ls -l bin/*.apk
          fi

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
          if-no-files-found: error
