name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    
      # Step 1: Check out the code
      - name: Check out repository
        uses: actions/checkout@v3  # Node 20 compatible version

      # Step 2: Set up Node.js (if required by the workflow)
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Ensures Node 20 is used
        with:
          node-version: '20'

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4 for Node.js 20 compatibility
        with:
          python-version: '3.9'

      # Step 4: Install Buildozer dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            libffi-dev \
            libltdl-dev \
            libssl-dev \
            libxml2-dev \
            libxslt1-dev \
            openjdk-11-jdk \
            pkg-config \
            python3-pip \
            unzip \
            zlib1g-dev
          pip install --upgrade pip
          pip install buildozer

      # Step 5: Build the APK using Buildozer
      - name: Build APK
        run: |
          buildozer init  # Initialize if needed
          buildozer android debug  # Builds the APK in debug mode

      # Step 6: Upload the APK to GitHub Artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my_kivy_app.apk
          path: bin/*.apk  # Path where the APK is stored
