name: Build APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.9'

      - name: Install Android SDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Android SDK components
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;33.0.0" "platforms;android-33" "cmdline-tools;latest"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            libffi-dev \
            libltdl-dev \
            libssl-dev \
            libxml2-dev \
            libxslt1-dev \
            openjdk-11-jdk \
            pkg-config \
            python3-pip \
            python3-dev \
            unzip \
            zlib1g-dev \
            libstdc++6  # Install libstdc++6 for aidl
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "tools"
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Clear GitHub Action cache (optional)
        run: |
          sudo rm -rf ~/.cache/pip
          sudo rm -rf ~/.buildozer

      - name: Build APK
        id: buildozer
        run: |
          stdbuf -oL buildozer android debug | tail -n 100
          APK_PATH=$(find . -type f -name "*.apk" | head -n 1)
          echo "APK Path: $APK_PATH"
          echo "::set-output name=filename::$APK_PATH"

      - name: List Directory Structure
        run: |
          echo "Listing all files and directories:"
          ls -R   # Recursively lists all files and directories from the root of the workspace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my_kivy_app.apk
          path: ${{ steps.buildozer.outputs.filename }}
