name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.9'

      # Step 3: Install Android SDK and Java
      - name: Install Android SDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: '11'

      # Step 4: Install necessary Android SDK components
      - name: Install Android SDK components
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;33.0.0" "platforms;android-33" "cmdline-tools;latest"

      # Step 5: Install build dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            libffi-dev \
            libssl-dev \
            libxml2-dev \
            openjdk-11-jdk \
            python3-pip \
            python3-dev \
            unzip \
            zlib1g-dev
          sudo apt-get install -y libstdc++6

      # Step 6: Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install kivy==1.11.1 cython buildozer

      # Step 7: Build the APK
      - name: Build APK
        run: |
          buildozer android debug > build.log 2>&1
          if [ $? -ne 0 ]; then
            echo "Build failed. Displaying last 100 lines of log:"
            tail -n 100 build.log
            exit 1
          fi
        shell: bash

      # Step 8: Display Build Logs (optional for debugging)
      - name: Display Build Logs
        if: failure()
        run: cat build.log

      # Step 9: Upload generated APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my_kivy_app.apk
          path: bin/*.apk

    env:
      ANDROID_HOME: ${{ runner.tool_cache }}/android-sdk
      PATH: ${{ runner.tool_cache }}/android-sdk/cmdline-tools/latest/bin:${{ runner.tool_cache }}/android-sdk/platform-tools:${{ env.PATH }}
