name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code using the latest checkout version
      - name: Check out repository
        uses: actions/checkout@v3  # Explicitly set to Node 20 compatible version

      # Step 2: Set up Node.js to ensure Node 20 is used explicitly (if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Ensures Node 20 compatibility
        with:
          node-version: '20'
      
      # Step 3: Set up Python environment with Node 20 compatible setup-python version
      - name: Set up Python
        uses: actions/setup-python@v4  # Node 20 compatible
        with:
          python-version: '3.9'

      # Step 4: Install Buildozer and other dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            libffi-dev \
            libltdl-dev \
            libssl-dev \
            libxml2-dev \
            libxslt1-dev \
            openjdk-11-jdk \
            pkg-config \
            python3-pip \
            unzip \
            zlib1g-dev
          pip install --upgrade pip
          pip install buildozer

      # Step 5: Clear any potential cache issues (optional but recommended for debugging)
      - name: Clear GitHub Action cache (optional)
        run: |
          sudo rm -rf ~/.cache/pip
          sudo rm -rf ~/.buildozer

      # Step 6: Build the APK using Buildozer
      - name: Build APK
        run: |
          buildozer init  # Initialize if needed
          buildozer android debug  # Builds the APK in debug mode

      # Step 7: Upload the APK using the latest version of upload-artifact action
      - name: Upload APK
        uses: actions/upload-artifact@v3  # Updated to v3 to ensure Node 20 compatibility
        with:
          name: my_kivy_app.apk
          path: bin/*.apk  # Path where the APK is stored
